### PR TITLE
Scala 2/3: Self-types

### PR DESCRIPTION
**Pull request by eed3si9n**
Fixes https://github.com/tree-sitter/tree-sitter-scala/issues/114

Picking off a commit from @keynmol's branch.

### CODE REVIEW

**Comment by eed3si9n** [comment]
Smoke test caught that this regresses on parsing the following apprently:

```scala
private[typechecker] def isFullyDefined(tp: Type): Boolean =
  tp match {
    case TypeVar(_, constr) if constr.inst == NoType => false
  }
```

**Comment by eed3si9n** [comment]
Actually I think that particular pattern seems to be broken on master as well? I think we should take the hit on Scala 2 compiler regression and merge this as-is.

**Comment by ckipp01** [comment]
> Actually I think that particular pattern seems to be broken on master as well? I think we should take the hit on Scala 2 compiler regression and merge this as-is.

I'm fine with that.

Also regarding what @keynmol said in the other pr:

> For this and future changes may I suggest adding highlighting tests as well to https://github.com/tree-sitter/tree-sitter-scala/blob/master/test/highlight/scala3.scala?

I don't want to press, since you're doing all the work here 😆, but should we add these, or tackle them later? If you don't want to I'm happy to try and go back through and add some when. I get some more time.

**Comment by eed3si9n** [comment]
> Also regarding what @keynmol said in the other pr:
> 
> > For this and future changes may I suggest adding highlighting tests as well to https://github.com/tree-sitter/tree-sitter-scala/blob/master/test/highlight/scala3.scala?

Sure. I added highlight for self-type.

**Pull request merged**
