### PR TITLE
Nvim indents

### PR DESCRIPTION
**Pull request by susliko**
Sharing queries for proper indents (also fixes problem descirbed in #173).
I'm going to use them for a while and polish before merging

cc @keynmol

### CODE REVIEW

**Comment by susliko** [comment]
TODO
```scala
object Foo:
  class Bar:<cr>
```
---

**Comment by farnoy** [comment]
Hey @susliko , how is your experience so far with this change? If it's not regressing anything else, maybe it may be worth merging to have an incremental improvement?

**Comment by susliko** [comment]
I've been using these indentation queries for neovim for a while now and I find them to be more or less satisfactory.

**Review by eed3si9n — APPROVED** [review]
Thanks!

**Pull request merged**
