### PR TITLE
Extension method support

### PR DESCRIPTION
**Pull request by eed3si9n**
Fixes https://github.com/tree-sitter/tree-sitter-scala/issues/74

### CODE REVIEW

**Review by ckipp01 — CHANGES_REQUESTED** [review]
Nice, LGTM!

**Review by ckipp01 — APPROVED** [review]
Sorry hit the wrong button. 🟢

**Comment by antonsviridov-clearscore** [comment]
For this and future changes may I suggest adding highlighting tests as well to https://github.com/tree-sitter/tree-sitter-scala/blob/master/test/highlight/scala3.scala?

**Comment by gvolpe** [comment]
Newbie tree-sitter user here: Shouldn't the `highlights.scm` file have been updated with the `extension` keyword as well? Or that will be added later on? Thanks a lot for the work you guys are doing here, so exciting!

**Comment by keynmol** [comment]
@gvolpe that's what my previous comment (under different account) was about :P 

I added extension to keywords here: https://github.com/tree-sitter/tree-sitter-scala/pull/120

**Comment by gvolpe** [comment]
Oh nooice! You guys are committing changes faster than I can click 🤣 , keep it up!

**Pull request merged**
